/*
  Late Fee Module FDD v2 (docs/product/LATE_FEE_FDD.md) / Implementation
  Roadmap v2 (docs/product/LATE_FEE_IMPLEMENTATION_ROADMAP.md), Sprint 1.

  Purely additive -- two new enums, two new tables, two new nullable/
  defaulted columns on the existing LateFee table. No existing row in
  LateFee needs touching for this migration to succeed; every pre-existing
  row remains valid with ruleId=NULL, usedFallbackConfig=false (the
  "resolution was never attempted" case, distinct from the "resolution
  ran and found nothing" case Sprint 2's fallback path will produce --
  see the column comment on LateFee.usedFallbackConfig in
  discounts.prisma).

  No SQL-level id DEFAULT on either new table: this repo's established
  standard (confirmed directly against LateFee's own original migration,
  and against src/scripts/backfill-discount-categories.ts's explicit
  header comment) is that cuid ids are generated by Prisma Client at
  insert time, not by a database-level default -- both new tables here
  are written exclusively through Prisma Client (the Sprint 1 seed
  script, and the Sprint 3 Rules service), never raw SQL, so this holds.

  getTenantConfig() does not read either new table yet -- that's Sprint
  2. This migration and the seed script that follows it are inert from
  the running application's point of view until Sprint 2 ships.
*/

-- CreateEnum
CREATE TYPE "LateFeeCalculationMethod" AS ENUM ('FLAT', 'PERCENTAGE', 'SLAB');
CREATE TYPE "LateFeePenaltyType" AS ENUM ('FLAT', 'PERCENTAGE');

-- CreateTable
CREATE TABLE "LateFeeRule" (
    "id"                TEXT NOT NULL,
    "tenantId"          TEXT NOT NULL,
    "branchId"          TEXT,
    "feePlanId"         TEXT,
    "calculationMethod" "LateFeeCalculationMethod" NOT NULL,
    "penaltyType"       "LateFeePenaltyType" NOT NULL,
    "penaltyValue"      DECIMAL(10,4) NOT NULL,
    "gracePeriodDays"   INTEGER NOT NULL,
    "maxPenalty"        DECIMAL(12,2),
    "compoundDaily"     BOOLEAN NOT NULL DEFAULT false,
    "slabSteps"         JSONB,
    "effectiveFrom"     TIMESTAMP(3) NOT NULL,
    "effectiveUntil"    TIMESTAMP(3),
    "isActive"          BOOLEAN NOT NULL DEFAULT true,
    "createdById"       TEXT,
    "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LateFeeRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LateFeeWaiver" (
    "id"         TEXT NOT NULL,
    "lateFeeId"  TEXT NOT NULL,
    "amount"     DECIMAL(12,2) NOT NULL,
    "waivedById" TEXT NOT NULL,
    "waivedAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason"     TEXT NOT NULL,

    CONSTRAINT "LateFeeWaiver_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
-- Sprint 1 risk mitigation (roadmap Section 10): a double-run of the seed
-- script must fail loudly against this constraint rather than silently
-- creating an ambiguous duplicate default at the same scope. A plain
-- UNIQUE(tenantId, branchId, feePlanId, effectiveFrom) does NOT achieve
-- this -- verified directly by executing it against Postgres before
-- shipping this migration: Postgres treats NULL as never equal to NULL,
-- so a naive unique constraint silently allows two Tenant-scope rules
-- (branchId/feePlanId both NULL) to coexist, which is exactly the case
-- Sprint 1's seed script creates. COALESCE to '' makes NULL a comparable
-- value for this index's purposes -- branchId/feePlanId are never
-- legitimately empty-string in this schema, only a real id or NULL, so
-- '' is a safe, unambiguous sentinel.
CREATE UNIQUE INDEX "LateFeeRule_scope_effectiveFrom_key" ON "LateFeeRule"
  ("tenantId", COALESCE("branchId", ''), COALESCE("feePlanId", ''), "effectiveFrom");
-- The exact shape Sprint 2's resolution chain queries by (roadmap Section 3).
CREATE INDEX "LateFeeRule_tenantId_branchId_feePlanId_isActive_idx"
  ON "LateFeeRule"("tenantId", "branchId", "feePlanId", "isActive");

-- CreateIndex
CREATE INDEX "LateFeeWaiver_lateFeeId_idx" ON "LateFeeWaiver"("lateFeeId");

-- AddForeignKey
ALTER TABLE "LateFeeRule" ADD CONSTRAINT "LateFeeRule_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LateFeeRule" ADD CONSTRAINT "LateFeeRule_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LateFeeRule" ADD CONSTRAINT "LateFeeRule_feePlanId_fkey" FOREIGN KEY ("feePlanId") REFERENCES "FeePlan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LateFeeRule" ADD CONSTRAINT "LateFeeRule_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LateFeeWaiver" ADD CONSTRAINT "LateFeeWaiver_lateFeeId_fkey" FOREIGN KEY ("lateFeeId") REFERENCES "LateFee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LateFeeWaiver" ADD CONSTRAINT "LateFeeWaiver_waivedById_fkey" FOREIGN KEY ("waivedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AlterTable: LateFee gains ruleId (nullable FK) and usedFallbackConfig
-- (defaulted, so every pre-existing row is valid with no data change).
ALTER TABLE "LateFee" ADD COLUMN "ruleId" TEXT;
ALTER TABLE "LateFee" ADD COLUMN "usedFallbackConfig" BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX "LateFee_ruleId_idx" ON "LateFee"("ruleId");
ALTER TABLE "LateFee" ADD CONSTRAINT "LateFee_ruleId_fkey" FOREIGN KEY ("ruleId") REFERENCES "LateFeeRule"("id") ON DELETE SET NULL ON UPDATE CASCADE;
