          tablename          
-----------------------------
 AcademicCalendarEvent
 AcademicCalendarEventTarget
 AcademicSession
 Admission
 AdmissionActivity
 AdmissionApplication
 AdmissionStepLog
 Alumni
 Announcement
 ApplicationApproval
 ApprovalWorkflowConfig
 Attendance
 AuditLog
 BehaviorRecord
 Book
 BookIssue
 Branch
 BulkNotificationJob
 Campaign
 Circular
 Class
 CommunicationLog
 CommunicationPolicy
 CommunicationTemplate
 Complaint
 ComplaintActivity
 Coupon
 CronExecutionLog
 Discount
 DiscountApproval
 DiscountCategory
 Document
 DunningAttempt
 EventOutbox
 Exam
 ExamSchedule
 Expense
 Family
 FeatureFlag
 FeatureFlagCacheVersion
 FeatureFlagOverride
 FeatureFlagOverrideRequest
 FeatureFlagSchedule
 FeatureFlagUsage
 FeeAssignment
 FeeItem
 FeePlan
 FeeStructure
 FeeType
 FollowUpTask
 FraudAlert
 GradeBoundary
 Guardian
 GuardianStudent
 Homework
 HomeworkSubmission
 House
 IDCard
 IDCardTemplate
 InteractionLog
 Invoice
 InvoiceItem
 JoiningApproval
 JoiningRequest
 LateFee
 Lead
 LeadSource
 LeaveBalance
 LeaveRequest
 License
 LicenseOrder
 Mark
 Notification
 NotificationLog
 NotificationPreference
 NotificationSetting
 OAuthAccount
 Payment
 PayrollEntry
 PayrollStructure
 Permission
 PricingPlan
 PromotionRule
 Receipt
 Refund
 Role
 RolePermission
 SaasInvoice
 SaasPayment
 Section
 Session
 Staff
 StaffAttendance
 StaffLeave
 StaffProfile
 StockItem
 Student
 StudentDailyCount
 StudentMigration
 StudentPromotion
 StudentRelationship
 StudentSibling
 Subject
 SupportMessage
 SupportTicket
 TeacherAssignment
 TeacherSubjectPreference
 Tenant
 TenantBranding
 TenantFeatureMatrix
 TenantJobSchedule
 TenantSecuritySettings
 TenantSettings
 TenantSubscription
 TimetableSlot
 TransportAssignment
 TransportRoute
 UsageRecord
 User
 UserBranch
 UserPermission
 Vendor
 VendorContract
 VendorProfile
 VendorPurchaseOrder
 VendorQuote
 Visitor
 _FeatureFlagToTenant
 _prisma_migrations
 admissionActivity
 asset
 maintenanceLog
(132 rows)

