import { htmlWrapper } from '../generators/html';
import { formatShortDate } from '../helpers';

export function hallTicketTemplate(data: {
  examName: string; schoolName: string; studentName: string;
  admissionNo: string; rollNumber?: string; className: string;
  schedules: { subject: string; date: string; startTime: string; endTime: string; hallId?: string }[];
}): string {
  const rows = data.schedules.map(s => `
    <tr>
      <td>${s.subject}</td>
      <td>${formatShortDate(s.date)}</td>
      <td>${s.startTime} – ${s.endTime}</td>
      <td>${s.hallId ?? '—'}</td>
    </tr>
  `).join('');

  return htmlWrapper(`Hall Ticket — ${data.studentName}`, `
    <div style="border:2px solid #1e293b;padding:20px;margin-bottom:20px">
      <div style="display:flex;justify-content:space-between">
        <div><h1>${data.schoolName}</h1><h2 style="color:#64748b;font-weight:normal">${data.examName}</h2></div>
        <div style="text-align:right;border:1px solid #e2e8f0;padding:12px;min-width:80px;min-height:80px;display:flex;align-items:center;justify-content:center">
          <span class="text-muted text-sm">Photo</span>
        </div>
      </div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px">
        <div><span class="text-muted text-sm">Name:</span> <strong>${data.studentName}</strong></div>
        <div><span class="text-muted text-sm">Adm No:</span> <strong>${data.admissionNo}</strong></div>
        <div><span class="text-muted text-sm">Class:</span> <strong>${data.className}</strong></div>
        ${data.rollNumber ? `<div><span class="text-muted text-sm">Roll No:</span> <strong>${data.rollNumber}</strong></div>` : ''}
      </div>
    </div>
    <table>
      <thead><tr><th>Subject</th><th>Date</th><th>Time</th><th>Hall / Room</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div style="margin-top:30px;display:flex;justify-content:space-between;font-size:11px;color:#94a3b8">
      <div>This hall ticket is required for examination entry</div>
      <div>Generated by SchoolOS</div>
    </div>
  `);
}
