import { htmlWrapper } from '../generators/html';
import { formatCurrency, formatDate } from '../helpers';

export function invoiceTemplate(data: {
  invoiceNumber: string; schoolName: string; studentName: string;
  admissionNo: string; className: string; items: { name: string; amount: number }[];
  subtotal: number; taxAmount: number; totalAmount: number; dueDate: string;
  currency?: string;
}): string {
  const cur = data.currency ?? 'INR';
  const rows = data.items.map(i => `
    <tr><td>${i.name}</td><td class="text-right">${formatCurrency(i.amount, cur)}</td></tr>
  `).join('');

  return htmlWrapper(`Invoice — ${data.invoiceNumber}`, `
    <div style="display:flex;justify-content:space-between;align-items:start;margin-bottom:30px;border-bottom:2px solid #1e293b;padding-bottom:20px">
      <div><h1>${data.schoolName}</h1></div>
      <div class="text-right"><h2>INVOICE</h2><div class="text-muted text-sm">${data.invoiceNumber}</div></div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:24px">
      <div><div class="text-muted text-sm">BILLED TO</div><div class="font-bold">${data.studentName}</div><div class="text-sm">${data.admissionNo} · ${data.className}</div></div>
      <div class="text-right"><div class="text-muted text-sm">DUE DATE</div><div class="font-bold">${formatDate(data.dueDate)}</div></div>
    </div>
    <table><thead><tr><th>Description</th><th class="text-right">Amount</th></tr></thead>
    <tbody>${rows}</tbody></table>
    <div style="margin-top:16px;text-align:right;border-top:2px solid #1e293b;padding-top:12px">
      <div class="text-sm text-muted">Subtotal: ${formatCurrency(data.subtotal, cur)}</div>
      ${data.taxAmount > 0 ? `<div class="text-sm text-muted">Tax: ${formatCurrency(data.taxAmount, cur)}</div>` : ''}
      <div class="font-bold" style="font-size:18px;margin-top:4px">Total: ${formatCurrency(data.totalAmount, cur)}</div>
    </div>
    <div style="margin-top:40px;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px">
      Generated by SchoolOS · ${new Date().toLocaleDateString('en-IN')}
    </div>
  `);
}
