/*
  Phase 2 (Billing Domain Model / PHASE_2_REVISED_REUSE_CLASSIFICATION.md,
  frozen). Purely additive: two new enums, one new table, four new nullable
  columns on the existing FeeItem table. No existing row needs touching for
  this migration to succeed -- every pre-existing FeeItem stays valid with
  feeHeadId/billingRuleId/effectiveFrom/effectiveUntil all NULL.

  No SQL-level id DEFAULT on BillingRule, matching this repo's established
  standard (cuid ids are generated by Prisma Client at insert time, not by
  a database-level default -- confirmed against every prior migration in
  this schema, e.g. LateFeeRule's own id column).

  Corrected in place, before deployment: BillingRule originally shipped
  without branchId -- an omission, not a decision, confirmed against
  LateFeeRule (the exact model this create-only design cited as its
  pattern), which already has one. Corrected here directly rather than as
  a separate follow-up migration, since this migration has not been
  applied to any persistent database.
*/

-- CreateEnum
CREATE TYPE "BillingFrequency" AS ENUM ('ONE_TIME', 'MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'ANNUAL', 'CUSTOM');
CREATE TYPE "ProrationRule" AS ENUM ('NO_PRORATION', 'DAILY', 'FULL_MONTH_IF_BEFORE_15TH', 'HALF_MONTH_AFTER_15TH');

-- CreateTable
CREATE TABLE "BillingRule" (
    "id"            TEXT NOT NULL,
    "tenantId"      TEXT NOT NULL,
    "branchId"      TEXT,
    "frequency"     "BillingFrequency" NOT NULL,
    "billingMonths" INTEGER[],
    "dueDayOfMonth" INTEGER NOT NULL,
    "prorationRule" "ProrationRule" NOT NULL DEFAULT 'NO_PRORATION',
    "createdAt"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BillingRule_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BillingRule_tenantId_idx" ON "BillingRule"("tenantId");
CREATE INDEX "BillingRule_tenantId_branchId_idx" ON "BillingRule"("tenantId", "branchId");

-- AddForeignKey
ALTER TABLE "BillingRule" ADD CONSTRAINT "BillingRule_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BillingRule" ADD CONSTRAINT "BillingRule_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AlterTable: FeeItem gains feeHeadId/billingRuleId/effectiveFrom/effectiveUntil,
-- all nullable -- every pre-existing row remains valid with no data change.
ALTER TABLE "FeeItem" ADD COLUMN "feeHeadId" TEXT;
ALTER TABLE "FeeItem" ADD COLUMN "billingRuleId" TEXT;
ALTER TABLE "FeeItem" ADD COLUMN "effectiveFrom" TIMESTAMP(3);
ALTER TABLE "FeeItem" ADD COLUMN "effectiveUntil" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "FeeItem_feeHeadId_idx" ON "FeeItem"("feeHeadId");
CREATE INDEX "FeeItem_billingRuleId_idx" ON "FeeItem"("billingRuleId");

-- AddForeignKey
ALTER TABLE "FeeItem" ADD CONSTRAINT "FeeItem_feeHeadId_fkey" FOREIGN KEY ("feeHeadId") REFERENCES "FeeHead"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "FeeItem" ADD CONSTRAINT "FeeItem_billingRuleId_fkey" FOREIGN KEY ("billingRuleId") REFERENCES "BillingRule"("id") ON DELETE SET NULL ON UPDATE CASCADE;
