// Single source of truth for creating a branch's default DiscountCategory
// records. Every caller -- OnboardingService (primary branch),
// SchoolManagementService.createBranch() (additional branches), and the
// one-time backfill script -- goes through this service. Nothing else may
// write DiscountCategory rows.
//
// Explicitly NOT a runtime auto-provisioner: DiscountService.create() resolves
// an existing category and rejects if it is missing. Financial master data is
// never created as a side effect of a transactional write.

import { Injectable, Logger } from '@nestjs/common';
// Moved to @infra/database now that AuditService is a second consumer -- as
// the note that used to sit here said to do. Re-exported so existing importers
// of this symbol from this module keep working.
import type { PrismaTransactionClient } from '@infra/database/prisma-transaction.type';
export type { PrismaTransactionClient };
import {
  DEFAULT_DISCOUNT_CATEGORIES,
  DiscountCategoryTemplate,
} from '../constants/default-discount-categories';

/**
 * Shape worth copying for future branch defaults (fee categories, document
 * types, assessment templates): defaults live in their own constants file as
 * data; one service owns writing them; the write joins the caller's
 * transaction; the operation is idempotent.
 *
 * That is guidance, not a contract -- there is deliberately no shared
 * interface, because a single implementation cannot justify an abstraction
 * nothing consumes (IMPLEMENTATION_RULES.md §3). Introduce one if and when a
 * caller actually needs to treat provisioners polymorphically.
 */
@Injectable()
export class DiscountCategoryProvisioningService {
  private readonly logger = new Logger(DiscountCategoryProvisioningService.name);

  /** The defaults this service provisions. Exposed for tests and tooling. */
  get templates(): readonly DiscountCategoryTemplate[] {
    return DEFAULT_DISCOUNT_CATEGORIES;
  }

  /**
   * Create the default categories for a branch, inside the caller's transaction.
   *
   * Idempotent by construction: existing (branchId, code) rows are read first
   * and skipped, so a retry, a partial failure, or a backfill pass over an
   * already-provisioned branch is safe and non-duplicating. The DB-level
   * @@unique([branchId, code]) is the backstop if two provisioning attempts
   * race; callers run inside a transaction, so the loser rolls back.
   *
   * IDs are generated by Prisma Client's @default(cuid()) -- this is precisely
   * why provisioning (including the backfill) runs through application code
   * rather than raw SQL, which cannot produce cuids.
   */
  async provisionForBranch(
    tx: PrismaTransactionClient,
    tenantId: string,
    branchId: string,
  ): Promise<{ created: number; skipped: number }> {
    const existing = await tx.discountCategory.findMany({
      where: { branchId },
      select: { code: true },
    });
    const existingCodes = new Set(existing.map((c: { code: string }) => c.code));

    const missing = DEFAULT_DISCOUNT_CATEGORIES.filter(
      (t) => !existingCodes.has(t.code),
    );

    if (missing.length > 0) {
      await tx.discountCategory.createMany({
        data: missing.map((t) => ({
          tenantId,
          branchId,
          code: t.code,
          name: t.name,
          isActive: true,
        })),
      });
    }

    const result = {
      created: missing.length,
      skipped: DEFAULT_DISCOUNT_CATEGORIES.length - missing.length,
    };

    this.logger.log(
      `Branch ${branchId}: provisioned ${result.created} default discount ` +
        `categor${result.created === 1 ? 'y' : 'ies'}, skipped ${result.skipped} existing.`,
    );

    return result;
  }
}
