export const PERMISSIONS = [
  'VIEW_STUDENTS',
  'CREATE_STUDENT',
  'EDIT_STUDENT',
  'DELETE_STUDENT',

  'VIEW_GRADES',
  'EDIT_GRADES',
  'PUBLISH_GRADES',

  'VIEW_INVOICES',
  'CREATE_INVOICE',
  'VOID_INVOICE',

  'VIEW_PAYMENTS',
  'PROCESS_PAYMENT',
  'REFUND_PAYMENT',

  'APPROVE_DISCOUNT',
  'APPROVE_DISCOUNT_UNLIMITED',

  'VIEW_TRANSPORT',
  'MANAGE_TRANSPORT',

  'VIEW_REPORTS',
  'EXPORT_REPORTS',

  'MANAGE_USERS',
  'MANAGE_ROLES',

  'VIEW_AUDIT_LOG',

  'MANAGE_FEE_PLANS',
  'MANAGE_SETTINGS',

  'VIEW_FRAUD_ALERTS',
  'RESOLVE_FRAUD_ALERTS',

  'SUPERADMIN_ALL',
] as const

export type Permission = (typeof PERMISSIONS)[number]
