/*
  Phase 4 (BillingRun, BillingRunAttempt, Invoice Builder, frozen).
  Purely additive -- two new tables, two new enums, no existing table
  altered.

  BillingRun_active_scope_unique enforces the frozen §6 rule directly at
  the database level, not just in application code: an active
  (non-terminal) BillingRun for the same tenant+branch+period cannot
  coexist with another. A partial index (WHERE status NOT IN
  ('COMPLETED','FAILED')), not a plain unique constraint -- a completed
  or failed run must not block a later, legitimate retry-by-new-run for
  the same scope; only an already-active one should.

  No SQL-level id DEFAULT on either table, matching this repo's
  established standard (cuid ids generated by Prisma Client at insert
  time), confirmed against every prior migration in this schema.
*/

-- CreateEnum
CREATE TYPE "BillingRunStatus"  AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'FAILED');
CREATE TYPE "BillingRunTrigger" AS ENUM ('SCHEDULED', 'MANUAL');
CREATE TYPE "AttemptStatus"     AS ENUM ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED');

-- CreateTable
CREATE TABLE "BillingRun" (
    "id"          TEXT NOT NULL,
    "tenantId"    TEXT NOT NULL,
    "branchId"    TEXT NOT NULL,
    "periodLabel" TEXT NOT NULL,
    "status"      "BillingRunStatus" NOT NULL DEFAULT 'PENDING',
    "triggeredBy" "BillingRunTrigger" NOT NULL,
    "startedAt"   TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdById" TEXT,

    CONSTRAINT "BillingRun_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "BillingRunAttempt" (
    "id"           TEXT NOT NULL,
    "tenantId"     TEXT NOT NULL,
    "billingRunId" TEXT NOT NULL,
    "studentId"    TEXT NOT NULL,
    "feePlanId"    TEXT,
    "status"       "AttemptStatus" NOT NULL DEFAULT 'PENDING',
    "retryCount"   INTEGER NOT NULL DEFAULT 0,
    "errorMessage" TEXT,
    "invoiceId"    TEXT,
    "completedAt"  TIMESTAMP(3),

    CONSTRAINT "BillingRunAttempt_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "BillingRun_tenantId_branchId_periodLabel_idx" ON "BillingRun"("tenantId", "branchId", "periodLabel");

-- CreateIndex: the frozen §6 run-level idempotency rule, at the
-- database level -- an active run blocks a second active run for the
-- same scope; a terminal one does not.
CREATE UNIQUE INDEX "BillingRun_active_scope_unique"
  ON "BillingRun" ("tenantId", "branchId", "periodLabel")
  WHERE "status" NOT IN ('COMPLETED', 'FAILED');

-- CreateIndex
CREATE UNIQUE INDEX "BillingRunAttempt_billingRunId_studentId_key" ON "BillingRunAttempt"("billingRunId", "studentId");
CREATE INDEX "BillingRunAttempt_tenantId_status_idx" ON "BillingRunAttempt"("tenantId", "status");
CREATE INDEX "BillingRunAttempt_tenantId_feePlanId_idx" ON "BillingRunAttempt"("tenantId", "feePlanId");

-- AddForeignKey
ALTER TABLE "BillingRun" ADD CONSTRAINT "BillingRun_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BillingRun" ADD CONSTRAINT "BillingRun_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "BillingRunAttempt" ADD CONSTRAINT "BillingRunAttempt_billingRunId_fkey" FOREIGN KEY ("billingRunId") REFERENCES "BillingRun"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "BillingRunAttempt" ADD CONSTRAINT "BillingRunAttempt_invoiceId_fkey"    FOREIGN KEY ("invoiceId")    REFERENCES "Invoice"("id")    ON DELETE SET NULL ON UPDATE CASCADE;
